BOMWhatsUp/rental_market_backend

src/main/java/com/bom/rentalmarket/s3/S3Service.java
Changes
---
Create 기능 개발중 AWS S3 upload 에 필요한 기능 개발
1. AWS S3 bucket 생성
2. AWS S3 client 연결 후 업로드 확인
---
//AWS SDK for java
implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
=> [200]-Rental-Create S3 upload 기능 추가

build.gradle
Changes
---
build.gradle 취합하여 업뎃합니다.
=> [000]-COMMON-GRADLE build.gradle 업뎃

build.gradle, src/main/java/com/bom/rentalmarket/common/config/SwaggerConfig.java
Changes
---
1. SWAGGER config 추가
2. build.gradle Modelmapper 추가
=> [001]-COMMON-SWAGGER

src/main/java/com/bom/rentalmarket/chatting/controller/ChatController.java, src/main/java/com/bom/rentalmarket/chatting/controller/ChatRoomController.java, src/main/java/com/bom/rentalmarket/chatting/domain/chat/ChatMessageForm.java, src/main/java/com/bom/rentalmarket/chatting/domain/model/ChatRoom.java, src/main/java/com/bom/rentalmarket/chatting/domain/repository/ChatRoomRepository.java, src/main/java/com/bom/rentalmarket/chatting/service/ChatRoomService.java, src/main/java/com/bom/rentalmarket/chatting/service/ChatService.java, src/test/java/com/bom/rentalmarket/chatting/controller/ChatRoomControllerTest.java, src/test/java/com/bom/rentalmarket/chatting/service/ChatRoomServiceTest.java, src/test/java/com/bom/rentalmarket/chatting/service/ChatServiceTest.java
Changes
---
코드 리팩토링
기존 채팅방 생성 시 chatroomName컬럼과 roomName 값을 UUID로 설정 하였으나, 굳이 roomName과 UUID가 필요 없어
roomId로 생성되도록 설정.
Testcode 작성
=> refactor: [303-chat_refactor] 코드 리팩토링 및 테스트 코드 작성

src/main/java/com/bom/rentalmarket/RentalMarketApplication.java, src/main/java/com/bom/rentalmarket/product/controller/ProductController.java, src/main/java/com/bom/rentalmarket/product/entity/ProductBoard.java, src/main/java/com/bom/rentalmarket/product/model/CreateProductForm.java, src/main/java/com/bom/rentalmarket/product/model/GetProductForm.java, src/main/java/com/bom/rentalmarket/product/service/ProductService.java, src/main/java/com/bom/rentalmarket/product/type/StatusType.java, src/main/java/com/bom/rentalmarket/s3/S3Service.java, src/main/resources/data.sql, src/main/resources/schema.sql
Changes
---
1. ProductBoard Entity 변수명 변경 및 추가 maxPeriod -> maxRentalPeriod (프론트와 맞춤) contents -> content region -> wishResion mainImageUrl (변수 추가) -> Create 시 선택된 이미지를 대표이미지로 설정함
2. CreateProductForm 변수명 변경 및 추가 1번과 동일한 사항 unitPrice type 변경 String -> Long
3. StatusType String 변경 UNAVAILABLE(대여불가) -> WAITING(반납대기)
4. RentalMarketApplication EC2Metadata disable
5. S3Service UUID 원본 이름 제거 및 파일이름만 리턴하도록 변경
6. ProductService Create 관련 service 내용 업데이트 mainImageIndex 전달받은 뒤 저장 1번가 동일한 사항으로 get,set 명칭 변경 Create시 modifiedAt 또한 내용이 기본적으로 null -> 생성된 날짜로 디폴트되게 하였음
7. ProductController Create Post 요청 시 ModelAttribute 어노테이션으로 Model속성으로 바인딩 이미지 객체는 filetype 타입이 image가 아닌것을 찾고, zip를 염려해 추가적으로 이미지 파일 확장자 구분을할 수 있는 조건문을 작성
---
추가적으로 Get 요청과 관련한 파일들도 있는데, 자주 PR하여 기능 분리해서 올리도록하겠습니다. 테스트를 위해 스키마 데이타 파일 sql도 …
=> [201]-Rental-Create 기능 구현

build.gradle, src/main/java/com/bom/rentalmarket/product/config/JpaConfig.java, src/main/java/com/bom/rentalmarket/product/controller/ProductController.java, src/main/java/com/bom/rentalmarket/product/model/CreateProductForm.java, src/main/java/com/bom/rentalmarket/product/service/ProductService.java, src/test/java/com/bom/rentalmarket/product/repository/ProductRepositoryTest.java, src/test/java/com/bom/rentalmarket/product/service/ProductGetServiceTest.java
Changes
---
0. queryDSL 추가함으로 아래 내용 추가
- build.gradle querydsl 관련 내용 추가
- product config에 JpaConfig 생성
1. CreateProductForm
- createAt, modifiedAt 추가
2. ProductController
- RequestMapping("/product") -> ("/products")로 변경
- GetMappinig 내용 추가
3. ProductService
- createProduct 로직 modelmapper 부분 삭제 -> builder로 바꿈
- getProducts 로직 추가
4. Get 구현에 따른 TestCode 작성
- repository 데이터 생성
- getProducts test code 작성
=> [202]-Rental-Get List

src/main/java/com/bom/rentalmarket/product/entity/RentalHistory.java, src/main/java/com/bom/rentalmarket/product/model/GetProductDetailForm.java, src/main/java/com/bom/rentalmarket/product/repository/RentalHistoryRepository.java
1. RentalHistory entity 작성
2. RentalHistoryRepository 작성
3. GetProductDetailForm 작성
=> [204]-Rental-RentalHistory

src/main/java/com/bom/rentalmarket/product/controller/ProductController.java, src/main/java/com/bom/rentalmarket/product/entity/RentalHistory.java, src/main/java/com/bom/rentalmarket/product/model/GetProductDetailForm.java, src/main/java/com/bom/rentalmarket/product/model/GetProductForm.java, src/main/java/com/bom/rentalmarket/product/model/GetRentalHistoryForm.java, src/main/java/com/bom/rentalmarket/product/repository/RentalHistoryRepository.java, src/main/java/com/bom/rentalmarket/product/service/ProductService.java
1. 오타 수정
2. GetProductForm
- returnDate 추가
3. GetRentalHistoryForm 추가
4. Controller GetProductDetail 추가
5. ProductService
- GetDetail 내용 추가
- GetList 부분 반납일 리턴 추가
=> [205]-Rental-GetDetail

build.gradle, src/main/java/com/bom/rentalmarket/RentalMarketApplication.java, src/main/java/com/bom/rentalmarket/product/controller/ProductController.java, src/main/java/com/bom/rentalmarket/product/model/CreateRentalHistoryForm.java, src/main/java/com/bom/rentalmarket/product/model/GetTransactionForm.java, src/main/java/com/bom/rentalmarket/product/service/ProductService.java, src/main/java/com/bom/rentalmarket/s3/S3Service.java, src/main/resources/data.sql, src/main/resources/schema.sql, src/test/java/com/bom/rentalmarket/product/service/ProductGetServiceTest.java
1. 오타 수정
2. GetTransactionForm 추가
3. ProductController
- 이름 가독성 있게 수정
- transaction 관련 controller 생성
4. ProductGetServiceTest
- 필요없는 부분 삭제
5. ProductService
- getProductTransaction 메서드 추가
- createRentalHistory 메서드 추가
6. RentalmarketApplication
- @EnableWebMvc 어노테이션 추가
- CORS 모든 요청을 받는 config를 추가했었는데 안되서 직접 설정해서 받게하려고 추가
- exclude ~ 추가 aws sdkexception 문제 해결
7. 기타
- schema,data 내용 추가
=> [206]-Rental-Transaction

src/main/java/com/bom/rentalmarket/RentalMarketApplication.java, src/main/java/com/bom/rentalmarket/S3/S3Config.java, src/main/java/com/bom/rentalmarket/s3/S3Service.java
1. S3Service 리팩토링을 하였습니다.
- S3config
- S3service
2. @EnableWebMvc 설정했더니 Localdatetime이 배열로 전달되는 현상이 있어서 지웠습니다.
- 자세한 내용은 노션에
=> [003]-S3-Service 리팩토링 수정

src/main/java/com/bom/rentalmarket/chatting/controller/ChatRoomController.java, src/main/java/com/bom/rentalmarket/chatting/service/ChatRoomService.java, src/test/java/com/bom/rentalmarket/chatting/controller/ChatRoomControllerTest.java, src/test/java/com/bom/rentalmarket/chatting/service/ChatRoomServiceTest.java, src/test/java/com/bom/rentalmarket/chatting/service/ChatServiceTest.java
Changes 
---
채팅방이 존재하는지 검증하는 로직 구현
- 유저 이름으로 roomId를 가져온 후 2명의 유저 roomId가 동일하다면 채팅방 생성 없이 /chat/room?roomId={roomId} 로 redirect
- 동일한 roomId가 없을 경우 방 생성 후 /chat/room?roomId={roomId} redirect
=> refactor: [305-already_chatroom] 채팅방이 존재하는지 검증

src/main/java/com/bom/rentalmarket/product/controller/ProductController.java, src/main/java/com/bom/rentalmarket/product/entity/RentalHistory.java, src/main/java/com/bom/rentalmarket/product/exception/ErrorResponse.java, src/main/java/com/bom/rentalmarket/product/exception/ProductControllerAdvice.java, src/main/java/com/bom/rentalmarket/product/model/GetProductDetailForm.java, src/main/java/com/bom/rentalmarket/product/repository/ProductSearch.java, src/main/java/com/bom/rentalmarket/product/repository/ProductSearchImpl.java, src/main/java/com/bom/rentalmarket/product/service/ProductService.java, src/test/java/com/bom/rentalmarket/product/service/ProductGetServiceTest.java
1. GetProductDetailForm
- sellerProfile (memeber.imageUrl) 추가
- sellerRegion (member.region) 추가
2. ProductController
- exception 부분 처리 진행중
3. ProductControllerAdvice 추가
- exception 관련 클래스
4. ErrorResponse 추가
- exception 관련 클래스
5. ProductGetServiceTest
- 페이지네이션 관련 Long type -> int로 변경
- db 성능 효율을 높이기위해 Long 보다는 int가 났다고해서...
- 또한 db에 int 범위를 넘는 그런 경우는 거의 없다고한다.
6. ProductSearch
- 위의 페이지네이션 관련 Long -> int
- 검색 필터를 위해 userRegion을 String으로 받음
7. ProductSearchImpl
- 검색 필터를 위해 userRegion을 String으로 받음
- 검색 필터 user의 대표 지역 필터링
8. ProductService
- 검색 필터를 위해 userRegion을 String으로 받음
- 검색 필터 user의 대표 지역 필터링
9. RentalHistory
- @ManyToOne 해제, 정확하게 사용방법을 모르기 때문에 직접 맵핑하는 쪽으로 하고 있음
=> [207]-Rental-GetDetail

build.gradle, src/main/java/com/bom/rentalmarket/product/controller/ProductController.java, src/main/java/com/bom/rentalmarket/product/service/ProductService.java, src/main/resources/data.sql, src/main/resources/schema.sql
0. build.gradle Security 주석처리 해제
1. data, schema 더미 데이타 업데이트
2. ProductController
- Transaction 시 CreateHistory부분 작성
3. ProductService
- 2번 과정 Service에 작성
=> [208]-Rental-Transaction 기능 구현중

build.gradle, src/main/java/com/bom/rentalmarket/UserController/controller/MemberController.java, src/main/java/com/bom/rentalmarket/UserController/domain/model/MemberUpdate.java, src/main/java/com/bom/rentalmarket/UserController/repository/MemberRepository.java, src/main/java/com/bom/rentalmarket/UserController/service/Impl/MemberServiceImpl.java, src/main/resources/schema.sql
0. build.gradle, schemar
- jwt 라이브러리 추가
- 오타 수정
1. MemberUpdate DTO
-  regin -> region 오타 수정
2. MemberController
- 2번 항목 오타로 관련된거 수정
3. MemberRepository
- findByIdAndPassword 삭제되어있음
4. MemberServiceImpl
- 3번 항목으로 인해 getUpdateMemberPassword 주석처리
2. ProductController
- Transaction 시 CreateHistory부분 작성
3. ProductService
- 2번 과정 Service에 작성
=> [101]-Member-common 기능 구현중

src/main/java/com/bom/rentalmarket/chatting/domain/model/RegisterRoom.java, src/main/java/com/bom/rentalmarket/chatting/domain/repository/RegisterRoomRepository.java
RegisterRoom static 팩토리 메서드 네이밍 변경
=> refactor: [306-refactor] 코드 리팩토링

src/main/java/com/bom/rentalmarket/chatting/controller/ChatRoomController.java, src/main/java/com/bom/rentalmarket/chatting/domain/chat/ChatListDto.java, src/main/java/com/bom/rentalmarket/chatting/domain/chat/ChatRoomDetailDto.java, src/main/java/com/bom/rentalmarket/chatting/domain/chat/ChatRoomUsers.java, src/main/java/com/bom/rentalmarket/chatting/domain/model/ChatRoom.java, src/main/java/com/bom/rentalmarket/chatting/domain/model/RegisterRoom.java, src/main/java/com/bom/rentalmarket/chatting/service/ChatRoomService.java, src/test/java/com/bom/rentalmarket/chatting/controller/ChatRoomControllerTest.java, src/test/java/com/bom/rentalmarket/chatting/service/ChatRoomServiceTest.java
Changes
---
채팅방 안에서 제품에 대한 정보 불러오기
채팅 목록에서 상품 이미지 불러오기
=> feat: [307-add_product_in_chatroom] 채팅방에 product 객체 추가

src/main/java/com/bom/rentalmarket/config/CorsConfig.java, src/main/java/com/bom/rentalmarket/product/controller/ProductController.java, src/main/java/com/bom/rentalmarket/product/entity/ProductBoard.java, src/main/java/com/bom/rentalmarket/product/entity/RentalHistory.java, src/main/java/com/bom/rentalmarket/product/exception/ProductControllerAdvice.java, src/main/java/com/bom/rentalmarket/product/model/GetProductDetailForm.java, src/main/java/com/bom/rentalmarket/product/model/GetProductForm.java, src/main/java/com/bom/rentalmarket/product/model/GetTransactionForm.java, src/main/java/com/bom/rentalmarket/product/repository/ProductRepository.java, src/main/java/com/bom/rentalmarket/product/repository/ProductSearch.java, src/main/java/com/bom/rentalmarket/product/repository/ProductSearchImpl.java, src/main/java/com/bom/rentalmarket/product/service/ProductService.java, src/test/java/com/bom/rentalmarket/product/service/ProductGetServiceTest.java
1.Product 리팩토링
- Member <-> ProductBoard 관계 적용
- email <-> sellerId @ManyToOne 관계를 적용함에 따라 내용 리팩토링
- 주요부분 ProductService - sellerId 부분
2. GetProducts 리스트 불러오는 부분 (ProductSearch, ProductService)
- 이슈 : 어제 테스트시 필터가 비정상 동작함
- 원인 : RentalHistory - product_id 관계를 삭제해놨었는데 여기서 문제가 됨, RentalHistory에서 returnDate를 가져오는 부분에서 에러가 발생
- 관계를 ManyToOne을 해놨으니까 나중에 한번 더 리팩토링 필요
3. CorsConfig 추가
=> [210]-Rental-Refactoring

src/main/java/com/bom/rentalmarket/product/service/ProductService.java
1. ProductService
- Transaction 미완성
=> [209]-Rental-Transaction

src/main/java/com/bom/rentalmarket/chatting/config/WebSocketConfig.java, src/main/java/com/bom/rentalmarket/chatting/config/handler/StompHandler.java
Changes
---
stomp jwt 검증 로직 구현
=> feat: [308-chat_validate_token] sotmp jwt 검증

src/main/java/com/bom/rentalmarket/chatting/domain/chat/ChatListDto.java, src/main/java/com/bom/rentalmarket/chatting/service/ChatRoomService.java
Changes
---
채팅방 전체 목록 조회시 셀러 프로필에 대한 이미지 불러오기 기능 추가
=> refactor: [309-chatroom_refactor] 채팅방 전체 리스트 조회할 때 셀러 프로필 불러오기

src/main/java/com/bom/rentalmarket/UserController/controller/MemberController.java, src/main/java/com/bom/rentalmarket/UserController/domain/model/MemberDto.java, src/main/java/com/bom/rentalmarket/UserController/domain/model/MemberInput.java, src/main/java/com/bom/rentalmarket/UserController/domain/model/entity/Member.java, src/main/java/com/bom/rentalmarket/UserController/repository/MemberRepository.java, src/main/java/com/bom/rentalmarket/config/SecurityConfig.java, src/main/java/com/bom/rentalmarket/config/WebAppConfiguration.java, src/main/java/com/bom/rentalmarket/jwt/JwtTokenProvider.java, src/main/java/com/bom/rentalmarket/service/CustomUserDetailService.java
=> [100] 회원가입, 로그인 수정

src/main/java/com/bom/rentalmarket/UserController/controller/MemberController.java, src/main/java/com/bom/rentalmarket/UserController/domain/model/MemberNickNameUpdate.java, src/main/java/com/bom/rentalmarket/UserController/domain/model/MemberRegionUpdate.java, src/main/java/com/bom/rentalmarket/UserController/repository/MemberRepository.java, src/main/java/com/bom/rentalmarket/config/WebAppConfiguration.java, src/main/java/com/bom/rentalmarket/service/LoginCheckService.java
=> [100] 회원가입, 로그인 수정, 중복체크 추가

src/main/java/com/bom/rentalmarket/product/controller/ProductController.java, src/main/java/com/bom/rentalmarket/product/entity/ProductBoard.java, src/main/java/com/bom/rentalmarket/product/entity/RentalHistory.java, src/main/java/com/bom/rentalmarket/product/model/CreateRentalHistoryForm.java, src/main/java/com/bom/rentalmarket/product/model/GetRentalHistoryForm.java, src/main/java/com/bom/rentalmarket/product/repository/RentalHistoryRepository.java, src/main/java/com/bom/rentalmarket/product/service/ProductService.java, src/main/java/com/bom/rentalmarket/product/type/MaxPeriodType.java, src/main/java/com/bom/rentalmarket/product/type/StatusType.java, src/main/java/com/bom/rentalmarket/s3/S3Service.java
1. CreateRentalHistoryForm
- 거래버튼을 눌렀을때 -> 내역 추가 하는 기능 완료
2. GetRentalHistoryForm
- 렌탈 내역 가져오기
3. MaxPeriodType
- 오타 수정
4. ProductBoard entity
- StatusType 변환하기 위해서 setStatus 추가
5. ProductController
- RequestMapping 삭제
- History 관련 Mapping 추가
6. ProductService
- History 관련 내용 추가
7. RentalHistory
- entity 추가
8. RentalHistoryRepository
- jpa 관련 검색 메서드 추가
=> [211]-Rental-History 렌탈 내역 기능 구현

src/main/java/com/bom/rentalmarket/chatting/controller/ChatRoomController.java, src/main/java/com/bom/rentalmarket/chatting/domain/chat/CreateRoomForm.java, src/main/java/com/bom/rentalmarket/chatting/domain/model/ChatRoom.java, src/main/java/com/bom/rentalmarket/chatting/domain/model/RegisterRoom.java, src/main/java/com/bom/rentalmarket/chatting/domain/repository/RegisterRoomRepository.java, src/main/java/com/bom/rentalmarket/chatting/service/ChatRoomService.java
Changes
---
최초 회원가입 시 nickname에 대한 중복 검증을 한다고 하여 채팅할 때 user nickname을 통해 채팅을 하므로 userId -> userNickname으로 코드 리팩토링
여러개의 채팅방이 하나의 제품을 가질 수 있기 때문에 OneToOne -> ManyToOne으로 변경
=> refactor: [310-chat_refactor] 채팅 유저 이름에 대한 코드 리팩토링

src/main/java/com/bom/rentalmarket/chatting/config/handler/StompHandler.java, src/main/java/com/bom/rentalmarket/chatting/exception/ChatCustomException.java, src/main/java/com/bom/rentalmarket/chatting/exception/ChatExceptionHandler.java, src/main/java/com/bom/rentalmarket/chatting/exception/ErrorCode.java, src/main/java/com/bom/rentalmarket/chatting/service/ChatRoomService.java
Changes
---
API 서버이므로 클라이언트에게 바로 응답을 전해줄 수 있도록 RestControllerAdvice를 활용하여 Exception 처리.
=> feat: [311-chat_exception] chat exception 구현

src/main/resources/application.yml
=> [004]-COMMON-GIT ACTION

src/main/resources/application.properties
=> [005]-COMMON-GIT ACTION

src/main/java/com/bom/rentalmarket/config/SecurityConfig.java, src/main/java/com/bom/rentalmarket/kakao/entity/SocialUser.java, src/main/java/com/bom/rentalmarket/kakao/repository/SocialUserRepository.java, src/main/java/com/bom/rentalmarket/kakao/service/KakaoService.java, src/main/java/com/bom/rentalmarket/kakao/type/SocialProvider.java, src/main/java/com/bom/rentalmarket/product/controller/ProductController.java, src/main/java/com/bom/rentalmarket/product/entity/RentalHistory.java, src/main/java/com/bom/rentalmarket/product/model/CreateRentalHistoryForm.java, src/main/java/com/bom/rentalmarket/product/model/UpdateRentalHistoryForm.java, src/main/java/com/bom/rentalmarket/product/service/ProductService.java
0. ProductController api 명칭 맞춤
1. Social 부분 업뎃
=> [400]-KAKAO-Social

src/main/java/com/bom/rentalmarket/config/CorsConfig.java, src/main/java/com/bom/rentalmarket/config/SecurityConfig.java, src/main/java/com/bom/rentalmarket/jwt/JwtAuthenticationFilter.java, src/main/java/com/bom/rentalmarket/jwt/JwtTokenProvider.java, src/main/java/com/bom/rentalmarket/product/controller/ProductController.java
1. Jwt 토큰 검증부분 get.Header 부분 프론트와 통일
2. CORS SecurityConfig 수정
3. SecurityConfig Cors 설정
=> [007]-COMMON-CORS Setting

src/main/java/com/bom/rentalmarket/RentalMarketApplication.java, src/main/java/com/bom/rentalmarket/config/SecurityConfig.java, src/main/java/com/bom/rentalmarket/product/model/RentalHistoryDetail.java, src/main/java/com/bom/rentalmarket/product/service/ProductService.java
1. History 페이지에서 운송장 보내는 페이지
- Controller에 적용
- ProductService 에 적용
2. RentalMarketApplication
- 스프링부트 시간 Asia/Seoul 로 지정
- 최초 시작시 설정됨
3. SecurityConfig
- /chatting/** 예외 페이지 적용
=> [212]-Rental-History Get Return

appspec.yml, scripts/deploy.sh
1. appspec.yml 추가
2. deploy.sh 추가
=> [008]-COMMON-GIT ACTION

src/main/java/com/bom/rentalmarket/chatting/controller/ChatRoomController.java, src/main/java/com/bom/rentalmarket/chatting/domain/repository/ChatMessageRepository.java, src/main/java/com/bom/rentalmarket/chatting/domain/repository/RegisterRoomRepository.java, src/main/java/com/bom/rentalmarket/chatting/service/ChatRoomService.java, src/main/java/com/bom/rentalmarket/chatting/service/ChatService.java
=> 312 chat refactor

src/main/java/com/bom/rentalmarket/chatting/config/WebSocketConfig.java, src/main/java/com/bom/rentalmarket/chatting/config/handler/StompHandler.java, src/main/java/com/bom/rentalmarket/chatting/config/kafka/KafkaConsumerConfig.java, src/main/java/com/bom/rentalmarket/chatting/config/kafka/KafkaProducerConfig.java, src/main/java/com/bom/rentalmarket/chatting/config/kafka/constants/KafkaConstans.java, src/main/java/com/bom/rentalmarket/chatting/controller/ChatController.java, src/main/java/com/bom/rentalmarket/chatting/domain/chat/NicknameVo.java, src/main/java/com/bom/rentalmarket/chatting/domain/repository/ChatMessageRepository.java, src/main/java/com/bom/rentalmarket/chatting/domain/repository/ChatRoomRepository.java, src/main/java/com/bom/rentalmarket/chatting/domain/repository/RegisterRoomRepository.java, src/main/java/com/bom/rentalmarket/chatting/service/ChatRoomService.java
Changes
---
채팅 외부 브로커로 카프카 연동.
Background
---
카프카 내부 동작 원리에 대한 공부
=> feature: [315-chat_External Broker] 채팅 외부 브로커 카프카 연동
